server:
  port: 8081
spring:
  main:
    banner-mode: 'off'
  mvc:
    favicon:
      enabled: false
    jmx:
      enabled: true
  artemis:
    transport: org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnectorFactory
#    host: broker-amq-tcp.amq-broker.svc
#    port: 61616
  cloud:
    stream:
      bindings:
        orderRequest:
          contentType: application/json
          destination: orderRequest
        orderResponse:
          contentType: application/json
          destination: orderResponse
          producer:
            headerMode: raw
springfox:
  documentation:
    swagger:
      v2:
        path: /v2/api-docs
