server:
  port: 8080
spring:
  main:
    banner-mode: 'off'
  mvc:
    favicon:
      enabled: false
    jmx:
      enabled: true
  artemis:
    transport: org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnectorFactory
    host: broker-amq-tcp.amq-broker.svc
    port: 61616
  cloud:
    stream:
      bindings:
        orderIn:
          contentType: application/json
          destination: orderIn
        orderOut:
          contentType: application/json
          destination: orderOut
          producer:
            headerMode: raw
#      artemis:
#        binder:
#          transport: org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnectorFactory
#          host: localhost
#          host: broker-amq-tcp.amq-broker.svc
#          port: 61616
springfox:
  documentation:
    swagger:
      v2:
        path: /v2/api-docs
