server:
  port: 8080
spring:
  main:
    banner-mode: 'off'
  mvc:
    favicon:
      enabled: false
  artemis:
    host: amq-demo-app-amq-tcp-amq7.172.120.0.1.nip.io
#    port: 61617
    port: 443
    user: demo
    password: redhat01
    sslEnabled: true
    keyStorePath: /home/rgordill/git/oc-cluster-wrapper/plugins.d/client.ks
    keyStorePassword: changeme
    trustStorePath: /home/rgordill/git/oc-cluster-wrapper/plugins.d/broker.ks
    trustStorePassword: changeme
    verifyHost: true
    useTopologyForLoadBalancing: false
  cloud:
    stream:
      bindings:
        orderRequest:
          contentType: application/json
          destination: orderRequest
        orderResponse:
          contentType: application/json
          destination: orderResponse
          producer:
            headerMode: raw
springfox:
  documentation:
    swagger:
      v2:
        path: /v2/api-docs
